version: '3.8'

services:
  prometheus:
    container_name: faf-hub-prometheus
    image: prom/prometheus
    networks:
      - faf-hub-network
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: faf-hub-grafana
    hostname: grafana
    image: grafana/grafana
    networks:
      - faf-hub-network
    ports:
      - ${GRAFANA_PORT}:3000
    depends_on:
      - prometheus

  postgres:
    container_name: faf-hub-postgres
    image: postgres:16
    networks:
      - faf-hub-network
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/faf-hub-db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres:/data/postgres
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s

  redis:
    container_name: faf-hub-redis
    image: redis:7.2.4
    networks:
      - faf-hub-network
    volumes:
      - redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}

  rabbitmq:
    container_name: faf-hub-rabbitmq
    image: rabbitmq:3-management
    networks:
      - faf-hub-network
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - "${AMQP_PORT}:5672"
      - "${RABBITMQ_PORT}:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s

  user_svc:
    container_name: faf-hub-user
    image: munchkin0812/faf-hub:user
    networks:
      - faf-hub-network
    depends_on:
      - postgres

  event_svc:
    container_name: faf-hub-event
    image: munchkin0812/faf-hub:event
    networks:
      - faf-hub-network
    depends_on:
      - postgres

  content_svc:
    container_name: faf-hub-content
    image: munchkin0812/faf-hub:content
    networks:
      - faf-hub-network
    depends_on:
      - postgres

  notification_svc:
    container_name: faf-hub-notification
    image: munchkin0812/faf-hub:notification
    networks:
      - faf-hub-network
    depends_on:
      - rabbitmq
    restart: on-failure

  gateway:
    container_name: faf-hub-gateway
    image: munchkin0812/faf-hub:gateway
    networks:
      - faf-hub-network
    ports:
      - ${APP_PORT}:5050
    depends_on:
      - redis
      - user_svc
      - event_svc
      - content_svc
      - notification_svc

volumes:
  postgres:
    driver: local
  redis:
    driver: local

networks:
  faf-hub-network:
    driver: bridge