version: '3.8'

services:
  postgres:
    container_name: faf-hub-db
    image: postgres:16
    networks:
      - faf-hub-network
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/faf-hub-db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres:/data/postgres
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s

  redis:
    container_name: faf-hub-redis
    image: redis:7.2.4
    networks:
      - faf-hub-network
    volumes:
      - redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  postgres:
    driver: local
  redis:
    driver: local

networks:
  faf-hub-network:
    driver: bridge